//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Carpeta.
        /// </summary>
        internal static string AddFolderButton {
            get {
                return ResourceManager.GetString("AddFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monitor de archivo.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar Datos.
        /// </summary>
        internal static string ClearDataButton {
            get {
                return ResourceManager.GetString("ClearDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_closed {
            get {
                object obj = ResourceManager.GetObject("eye_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_open {
            get {
                object obj = ResourceManager.GetObject("eye_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carpetas monitoreadas.
        /// </summary>
        internal static string FoldersLabel {
            get {
                return ResourceManager.GetString("FoldersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir Subcarpetas.
        /// </summary>
        internal static string IncludeSubfolders {
            get {
                return ResourceManager.GetString("IncludeSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10 minutos.
        /// </summary>
        internal static string Interval10Min {
            get {
                return ResourceManager.GetString("Interval10Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12 horas.
        /// </summary>
        internal static string Interval12Hours {
            get {
                return ResourceManager.GetString("Interval12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 15 minutos.
        /// </summary>
        internal static string Interval15Min {
            get {
                return ResourceManager.GetString("Interval15Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 hora.
        /// </summary>
        internal static string Interval1Hour {
            get {
                return ResourceManager.GetString("Interval1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 minutos.
        /// </summary>
        internal static string Interval1Min {
            get {
                return ResourceManager.GetString("Interval1Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 24 horas.
        /// </summary>
        internal static string Interval24Hours {
            get {
                return ResourceManager.GetString("Interval24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2 hora.
        /// </summary>
        internal static string Interval2Hours {
            get {
                return ResourceManager.GetString("Interval2Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 30 minutos.
        /// </summary>
        internal static string Interval30Min {
            get {
                return ResourceManager.GetString("Interval30Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4 horas.
        /// </summary>
        internal static string Interval4Hours {
            get {
                return ResourceManager.GetString("Interval4Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5 minutos.
        /// </summary>
        internal static string Interval5Min {
            get {
                return ResourceManager.GetString("Interval5Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 8 horas.
        /// </summary>
        internal static string Interval8Hours {
            get {
                return ResourceManager.GetString("Interval8Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intervalo de monitoreo.
        /// </summary>
        internal static string IntervalLabel {
            get {
                return ResourceManager.GetString("IntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap praxis_emr_logo {
            get {
                object obj = ResourceManager.GetObject("praxis_emr_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico del destinatario.
        /// </summary>
        internal static string RecipientEmailLabel {
            get {
                return ResourceManager.GetString("RecipientEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Carpeta.
        /// </summary>
        internal static string RemoveFolderButton {
            get {
                return ResourceManager.GetString("RemoveFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico del remitente.
        /// </summary>
        internal static string SenderEmailLabel {
            get {
                return ResourceManager.GetString("SenderEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Monitoreo.
        /// </summary>
        internal static string StartMonitoringButton {
            get {
                return ResourceManager.GetString("StartMonitoringButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detener Monitoreo.
        /// </summary>
        internal static string StopMonitoringButton {
            get {
                return ResourceManager.GetString("StopMonitoringButton", resourceCulture);
            }
        }
    }
}
